### ISSUE TITLE
nohup: failed to run command .../make.sh: Permission denied

### ISSUE THREAD

**Issue by JVerstry** [laobubu/openshift-php5.5-cgi-apache#1]
When I follow the instructions to install openshift-php5.5-cgi-apache, I get a Permission denied. How can this be solved? I have also opened a question on StackOverflow: http://stackoverflow.com/questions/31244142/how-to-install-php5-on-openshift?noredirect=1#comment50485873_31244142

**Comment by laobubu** [comment]
Maybe you are using Windows, which discards Linux permission information.

I just updated this repo. Please try it out! It's easier now!

**Comment by JVerstry** [comment]
I am indeed on Windows 7. I have tried with the updated repo, but still not luck. Here is what I did:
1. I am not really sure of what you mean when you say 'pushing' this repo into Openshift.
2. I have created a do-it-yourself application. I cloned it locally.
3. I cloned your repo locally. 
4. I deleted the content of my DIY repo, except the .git file.
5. I exported the content of your repo (everything but the .git) and copied it into my DIY repo.
6. I committed every changes and pushed them. It was a fast operation.
7. I browsed my URL and got: Internal Server Error - The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by laobubu** [comment]
The easiest way:
1. Open https://openshift.redhat.com/app/console/application_type/cart!diy-0.1 
2. Fill **Source Code** text field: `https://github.com/laobubu/openshift-php5.5-cgi-apache.git`
3. Click **Create Application** and wait
4. After creating the app, visit your app (e.g. https://foo-bar.rhcloud.com/ )
5. Click the last link.
6. Wait for ~1 hour and then PHP will be ready.
7. Git clone your OpenShift App and modify.

It's **not** a good idea to **copy files directly** when you are using Windows. There are lots of files whose permission information is essential. Git for Windows stores the permission information in `.git`, not in the files.

**Comment by JVerstry** [comment]
I had tried to use the repo directly when creating my DYI earlier but it did not work. This time it works. Thanks!
