### ISSUE TITLE
Enhancement request - To include Composer

### ISSUE THREAD

**Issue by JVerstry** [laobubu/openshift-php5.5-cgi-apache#2]
Hi, this is not an issue, but an enhancement request. It seems Composer is used both by Symfony and the Zend Framework. If its installation was included in your cartridge, it would crush all competition on Openshift and make everyone's PHP life easier (lol).

There is a possibility to trigger the execution of Composer with markers in the Openshift's 'supported' PHP cartridges (see https://developers.openshift.com/en/php-markers.html). This cartridge could implement the same.

The reason I am suggesting this is that currently, the skeleton Zend Framework application crashes on OpenShift: http://stackoverflow.com/questions/31473760/how-to-run-or-should-i-run-composer-on-openshift#31474327

**Comment by laobubu** [comment]
Composer is not the fundamental component. It can be added into the cartridge easily by adding OpenShift hooks.
