### ISSUE TITLE
Wrong PHP version returned in Openshift ssh after installation

### ISSUE THREAD

**Issue by JVerstry** [laobubu/openshift-php5.5-cgi-apache#3]
Hi, after creating the openshift application with the cartridge, the returned php --version in ssh is 5.3.3 while the make.sh version is 5.5.18. The php info page returns 5.5.18 too. This prevents the installation of Composer.

I have created a question on Stackoverflow (with more details and screen shots), because I don't know whether the issue lies here or on Openshift's side: http://stackoverflow.com/questions/31478610/wrong-php-version-returned-in-openshift. I know that the people from Openshift will see it there.

P.S.: Someone provided an possible explanation for this issue on the StackOverflow question. It seems the build is in the misc folder, not the runtime folder.

**Comment by laobubu** [comment]
If you run `php`, the shell uses OpenShift's own PHP (5.3.x).

To enable your own PHP, run this command:

```
export PATH=${OPENSHIFT_HOMEDIR}/app-root/runtime/bin/:${PATH}
```
