### ISSUE TITLE
wrong PHP version

### ISSUE THREAD

**Issue by iepster** [laobubu/openshift-php5.5-cgi-apache#4]
This is the php -v output on the server. What am I missing ?

PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.1.4, Copyright (c) 2002-2012, by Derick Rethans

**Comment by ghost** [comment]
See https://github.com/laobubu/openshift-php5.5-cgi-apache/issues/3

**Comment by laobubu** [comment]
Run `php` with full path, or modify environment variable `PATH` before running `php`
